name: Build/run unittests
on: [push]
jobs:
  build-unittests:
    container:
      image: ghcr.io/neocortec/neo.corepp:1.3
    runs-on: [ self-hosted, builder ]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout branch ${{ github.ref }} of repository ${{ github.repository }}."
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Build and run unittests
        # run: cd software && ./cmake_build_unittests.sh
