name: Build debug target
on: [push]
jobs:
  build-debug:
    container:
      image: unknown
    runs-on: [ self-hosted, builder ]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout branch ${{ github.ref }} of repository ${{ github.repository }}."
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Build debug target
        run: cd software && ./cmake_build_debug.sh
