name: Check code format with clang-format
on: [pull_request]
jobs:
  clang-format:
    container:
      image: unknown
    runs-on: [ self-hosted, builder ]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout branch ${{ github.ref }} of repository ${{ github.repository }}."
        uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Perform format check
        run: find ./software/src -iname "*.h" -o -iname "*.cpp" | xargs clang-format --Werror --dry-run 
